### ISSUE TITLE
Create a package for 1.64.0

### ISSUE THREAD

**Issue by liberforce** [conan-community/conan-boost#102]
Hi, would it be possible to have a branch for boost 1.64? There was a bunch of packages for that on conan-transit, but they're for conan < 1.0, and since the `Boost` -> `boost` renaming keeping old and new recipes doesn't work on Windows. This is because you can't have directories with the same name and different cases, so you can't parallel install a 1.64 recipe from conan-transit and `boost/1.66@conan/stable`.

I've successfully built a 1.64.0 based on your 1.66.0 recipe, by just [changing the version and checksums](https://github.com/liberforce/conan-boost/commit/1985ae5756f5929c0905427d22b4b1ab82f3cecb), but that's a bit stupid to have this kind of patching downstream. But I may have overlooked some problems with this approach and maybe just adapting your old 1.64 recipe would be better, I don't know.

So, could you please provide a 1.64 conan package that would be published on conan-center (maybe in `testing` channel, or `legacy` channel if you don't want to officially support that)? This will help people like me that can't depend on a too recent boost (we're still using 1.59 but I found that by using 1.64 our software would still build, but not with 1.66).

Thanks.

**Comment by helmesjo** [comment]
Any chance this could get some love? 1.64.0 feels like low-enough version to support most of those older libs using "legacy boost".

**Comment by lasote** [comment]
You are right, the `1.64.0` recipe is very very outdated. I've not tried it but in addition to change the version and checksum we probably need to change the libraries list. Also, I needed to change some boost build related scripts in 1.66 (If I recall correctly) so it is possible that it fails too. 
The only way we can try it is opening a pull request and see how the CI goes. 
I would need some help here, this is not a quick request.

**Comment by liberforce** [comment]
I was able to build boost 1.64 on Windows and Linux without problems, but didn't perform thourough testing on the generated binaries, so yeah, that might be more complicated.
I've created a PR against release/1.64, so there are lots of commits due to all the 1.64 → 1.66 activity, but mine is trivial. Let's see what the CI thinks about it.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#89
