### ISSUE TITLE
compile boost for python 3

### ISSUE THREAD

**Issue by mrmoon01** [conan-community/conan-boost#106]
Hello,

When I am trying to install boost with conan in my computer it is working. But for my other computer it does not create boost_python3.lib. It just creates boost_python.lib 

Here is my conanfile.txt

`[requires]
boost/1.66.0@conan/stable

[options]
boost:shared=False
boost:without_python=False
boost_python:python_version=3.6

[generators]
cmake
`

and win_profile.txt

`[settings]
arch=x86_64  
build_type=Release  
compiler=Visual Studio  
compiler.runtime=MD  
compiler.version=15  
os=Windows`  

I am typing in command line 
`conan install . --profile=win_profile.txt  --build missing`

Edit: I found the problem. It is about path variable which is set to C:\Python27 in my other computer. But the thinks is I want to force Conan to use python 3

**Comment by ArekPiekarz** [comment]
I may be wrong, but I believe the line `boost_python:python_version=3.6` doesn't do anything in your case, because you are not using modular `boost_python` package from bincrafters, only `boost` package from conan-center.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#85
