### ISSUE TITLE
Boost does not pick up bzip2 automatically

### ISSUE THREAD

**Issue by sturmf** [conan-community/conan-boost#116]
Hi,
on my windows build the boost build does not pick up bzip2. It gets automatically picked up if we also add the hints to the location and library name for windows as can be seen here:

https://github.com/conan-community/conan-boost/blob/2e5d045d03ef0f1bb641a23f41b88923ae61fb24/conanfile.py#L210

So my suggestion, remove the conditional for Linux and Macos only.

**Comment by lasote** [comment]
Thanks for reporting. I'll try to remove the line for windows and see what happens.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#88
