### ISSUE TITLE
cross compiling (mingw64 on linux64) boost 1.67 causes python back trace

### ISSUE THREAD

**Issue by pro-spero** [conan-community/conan-boost#122]
Using a x86_64-w64-mingw32-gcc toolchain on Linux64 results in an IndexError python error.

boost/1.67.0@conan/stable: ERROR: Package '58a05ff27c6e79fa9cbc477b413087211c40aff4' build failed
boost/1.67.0@conan/stable: WARN: Build folder /home/philipp.schwaha/.conan/data/boost/1.67.0/conan/stable/build/58a05ff27c6e79fa9cbc477b413087211c40aff4
ERROR: boost/1.67.0@conan/stable: Error in build() method, line 83
        self.create_user_config_jam(self.build_folder)
while calling 'create_user_config_jam', line 209
        self.deps_cpp_info["zlib"].lib_paths[0].replace('\\', '/'),
        IndexError: list index out of range

**Comment by lasote** [comment]
Related to https://github.com/conan-community/community/issues/29
It is not an issue with Boost but with zlib. It is being fixed.
But I could bet the Boost recipe won't work either. It will require some adjustments.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#82
