### ISSUE TITLE
Linking with a project with Boost fails since Boost 1.67.0

### ISSUE THREAD

**Issue by Johnnyxy** [conan-community/conan-boost#127]
Hi there,
I'm using conan to build boost from source (Windows 7 x64 VS2015 MD static).
With Boost 1.67.0 there was a [change](http://boost.2283326.n4.nabble.com/UUID-broken-with-Boost-1-67-and-VS2015-tp4703086p4703090.html) in the UUID lib from Boost ([link](http://boost.2283326.n4.nabble.com/UUID-broken-with-Boost-1-67-and-VS2015-tp4703086p4703090.html)).
It uses bcrypt from Windows by default as provider. This requires to link against [bcrypt.lib](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptopenalgorithmprovider).
The conan recipe for Boost disables the Boost autolinking feature with specifiing "BOOST_ALL_NO_LIB" that in turn does not link the bcrypt.lib automatically anymore ([see](https://github.com/boostorg/uuid/blob/405f9614312bb6d6d703d3b932f45bd7cb3b1a1e/include/boost/uuid/detail/random_provider_bcrypt.ipp#L20)).

Best regards

**Comment by Johnnyxy** [comment]
Fixed it locally by adding the following line in package_info function.
from:
```python
if self.settings.compiler == "Visual Studio":
    # DISABLES AUTO LINKING! NO SMART AND MAGIC DECISIONS THANKS!
    self.cpp_info.defines.extend(["BOOST_ALL_NO_LIB"])
```
to:
```python
if self.settings.compiler == "Visual Studio":
    # DISABLES AUTO LINKING! NO SMART AND MAGIC DECISIONS THANKS!
    self.cpp_info.defines.extend(["BOOST_ALL_NO_LIB"])
    self.cpp_info.libs.extend(["bcrypt.lib"])
```

**Comment by lasote** [comment]
Thanks for reporting. Is "bcrypt.lib" a Windows system library, right? Do you know if it is only for Visual Studio or also for Mingw?

**Comment by Johnnyxy** [comment]
Yes, this is a Microsoft-provided library for Windows (since Vista).

As I am not using MinGW at all, I cannot give you a definite answer. But after a quick search it seems to me that MinGW64 has a [bcrypt.lib/.dll](https://sourceforge.net/p/mingw-w64/mailman/message/36005555/) too ([see](https://sourceforge.net/p/mingw-w64/mailman/message/36005555/)).

I was looking into the sources of MinGW (32) at the awful sourceforge site, too. The source parts mingwrt-5.0.2 and w32api-5.0.2 of MinGW (32) do not have anything that relates to bcrypt at all.
Maybe there is more sources to crawl through but for that maybe a MinGW expert could tell us more about that.

**Comment by lasote** [comment]
We can start adding it only when Visual Studio and wait for feedback. No problem.

**Comment by Johnnyxy** [comment]
As a side note I think the commited fix https://github.com/conan-community/conan-boost/commit/d6a0358719cd92c9e18f7602c158205e88e20b25 will work for Visual Studio.

Here comes my inexperience with MinGW64. What if someone tries to compile MinGW64 with GCC. Then the "if" would not trigger and bcrypt would not be linked.

Have a look at my edit https://github.com/conan-community/conan-boost/issues/127#issuecomment-403762779.
``` python
if self.settings.os == "Windows":
    self.cpp_info.libs.extend(["bcrypt.lib"])
```
This would trigger on Windows in general as this is needed with any compiler using the Windows-BCrypt-API.

**Comment by lasote** [comment]
I know, but as it looked like we were (or at least myself) not sure about it is needed in Mingw I preferred to add it only for VS. If you confirm it is needed for mingw I will add it.

**Comment by Johnnyxy** [comment]
Ok. I misunderstood.
