### ISSUE TITLE
Cross compilation for powerpc architecture

### ISSUE THREAD

**Issue by oliverdaniell** [conan-community/conan-boost#136]
I've added support for powerpc builds in https://github.com/conan-community/conan-boost/compare/release/1.67.0...oliverdaniell:feature/powerpc

The main addition is the check for  the ```-mabi``` flag in ```CXXFLAGS``` as an alternative to inferring it from the architecture. This avoids hard-coding all the variants of the powerpc architecture into the conanfile.

If there is any interest in merging these changes I can create a pull request.

**Comment by lasote** [comment]
Hi! for sure it is interesting for the recipe. Just one question:

```python
        if "-mabi" in os.environ["CXXFLAGS"]:
            self.output.info("Cross building, setting abi from CXXFLAGS")
```

Why to check if "-mabi" is in the CXXFLAGS instead of comparing the architecture and set the flag?

**Comment by oliverdaniell** [comment]
>Why to check if "-mabi" is in the CXXFLAGS instead of comparing the architecture and set the flag?

Hi @lasote, several reasons for this. 
- It simplifies adding a new architecture. You just need to setup CXXFLAGS in the profile and most recipes will work out of the box. CMake and Autotools recipes already support this which makes boost the exception.
- There is not a one to one relationship between architectures and flags. There is usually a sensible default but users may wish to override it.
- ```mabi``` is not the only architecture dependent flag that needs to be set, for example the processor I'm currently building for requires ```-m32 -mcpu=8548 -mabi=spe -mspe -mfloat-gprs=double```
- The set of architectures currently defined in conan is not fine grained enough to correctly set the ```mabi``` flag. I'd need to add a PowerPC SPE architecture, and there are several other variants.

I'd be tempted to go further and set arch from a B2_ARCH environment variable. That would allow new architectures to be added from a profile without having to patch the conan boost recipe each time.

**Comment by lasote** [comment]
Fair enough. But then I would prefer  instead of `if "-mabi" in os.environ["CXXFLAGS"]:`:

```
if arch=="power":
    self.output.info("Cross building for powerpc")
```

**Comment by oliverdaniell** [comment]
Great, I'll make those changes and open a pull request

**Comment by oliverdaniell** [comment]
@lasote before I make any modifications I just want to check that the existing code is doing what we expect

This code appears to be appending a cxxflag to the boost build flags (my best guess is that this gets ignored)
```
if 'hf' in arch:
                flags.append('-mfloat-abi=hard')
```

I don't think abi is a recognized build option, there is a feature [c++abi](https://github.com/boostorg/build/search?q=feature.feature+abi&unscoped_q=feature.feature+abi)? 
```
flags.append('abi=aapcs')
```
I suspect this might be working because the correct flags are already set in CXXFLAGS for the test profile. Are you able to point me towards your CI setup so I can reproduce the test locally?

**Comment by lasote** [comment]
I think you are right about `-mfloat-abi=hard` looks like the flag shouldn't be there.
About the `abi`:
https://www.boost.org/doc/libs/1_66_0/libs/context/doc/html/context/architectures/crosscompiling.html

About how to reproduce it, it was added for Android, here we described how to setup the environment of the NDK but it is quite tedious:

https://blog.conan.io/2018/01/30/Cross-building-Boost-Android.html

**Comment by oliverdaniell** [comment]
Thanks for the links, it looks like I was confusing the boost context abi flag and the -mabi flag passed to C++ compiler. The abi flag for boost context is setting the abi for assembler, the -mabi flag is setting extensions to the default abi for the c++ compiler. I think I need to copy the arm setup and use ```flags.append('abi=sysv')```

https://www.boost.org/doc/libs/1_66_0/libs/context/doc/html/context/architectures.html

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#80
