### ISSUE TITLE
Fail to build on boost on Travis

### ISSUE THREAD

**Issue by rllola** [conan-community/conan-boost#138]
I am not able to build on Travis : 
https://travis-ci.org/rllola/zeronet-torrent-plugin/jobs/410820902

But on my local machine and vagrant (both 18.04) It is working file. Could someone tell me what I am doing wrong ?

**Comment by lasote** [comment]
I'm not sure, looks like a memory error or something?

**Comment by rllola** [comment]
Yes it looks like it. When I was building with boost 1.60 it was working fine. 

https://travis-ci.org/rllola/zeronet-torrent-plugin/builds/279321298

But 1.60 is not compatible with the latest version of conan. Any idea how I could do to try to solve this ?

**Comment by rllola** [comment]
Closing because it is not a bug but rather a problem with travis build in particular.
