### ISSUE TITLE
Option to disable BOOST_ALL_NO_LIB

### ISSUE THREAD

**Issue by WolfgangVogl** [conan-community/conan-boost#140]
Hello,
is there a specific reason to set BOOST_ALL_NO_LIB for visual studio?
It would be nice to have the possibility NOT to set the option...

 # DISABLES AUTO LINKING! NO SMART AND MAGIC DECISIONS THANKS!
    self.cpp_info.defines.extend(["BOOST_ALL_NO_LIB"])

See Pull Request #141

**Comment by lasote** [comment]
Merged!
