### ISSUE TITLE
No packages available for 1.68.0 for Linux

### ISSUE THREAD

**Issue by LauraBogdan** [conan-community/conan-boost#143]
Yet all the packages for windows are available.

**Comment by lasote** [comment]
Thanks, something failed in the linux/mac builds. Let me check and relaunch.

**Comment by Croydon** [comment]
There still seems to be no package for (at least) Clang 5

**Comment by lasote** [comment]
Please, specify the complete trace for the missing package, for example this one for clang 5 is present: 

'conan get boost/1.68.0@conan/stable -p 1cc2206afa37cd09efc31c5913e054039089f7c8 -r conan-center

**Comment by Croydon** [comment]
I'm not sure if this is all information you need, let me know if you need more:

>	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=clang
	compiler.version=5.0
	compiler.libcxx=libstdc++
	build_type=Release

https://travis-ci.org/inexorgame/inexor-core/jobs/423269281#L570
https://travis-ci.org/inexorgame/inexor-core/jobs/423269281#L792

**Comment by lasote** [comment]
These specific settings resolves to the package `boost/1.68.0@conan/stable:66ea23538750d0ff55320a0f64616b0b6ba3d9cb` that is present indeed. Probably you or one of your dependencies are changing some option?

**Comment by Croydon** [comment]
We are setting shared explicit to False, but that is all I'm aware about

https://github.com/inexorgame/inexor-core/blob/e2aa17cb224b09aa4a73b423802db7bf2edb6ccf/dependencies.py#L21

**Comment by lasote** [comment]
The `shared=False` is the default and resolves to `66ea23538750d0ff55320a0f64616b0b6ba3d9cb`. It has to be some more change maybe in an intermediate dep, let me check.

**Comment by lasote** [comment]
Now I see, from the command line you are appending `-s compiler.libcxx=libstdc++11` so the id is the missing one, but that is because conan package tools never generated `libstdc++11` packages for linux clang so far.

**Comment by lasote** [comment]
Actually the 1.66.0 has the same issue: boost/1.66.0@conan/stable:7e07acc0e70d88aaa1ddb206f621d8a2f03b7ba1 - Missing

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#79
