### ISSUE TITLE
LNK1104: cannot open file 'libboost_system-vc141-mt-sgd-x32-1_67.lib'

### ISSUE THREAD

**Issue by WolfgangVogl** [conan-community/conan-boost#147]
I'm building boost with conan using the visual_studio generator.
All's fine except the linker tells me it couln't find the libboost_system-vc141-mt-sgd-x32-1_67.lib.
The Problem is that I think it shouldn't look for the libboost_system-......lib version - the command line just mentions libboost_system (this would be okay and I expect it to work).
I've no idea how the linker comes to the filename with the full version number etc. in it.
I'm using a lot of the boost packages - the _system lib is the only one making truble.

Any ideas?
(libboost_system.lib is located in C:\.conan\qdrztniy\1\system\lib - this looks okay).

Conanfile.txt:
[requires]
...
boost/1.67.0@conan/stable
[generators]
visual_studio
[options]
boost:magic_autolink=True
...

conanbuildinfo.props
...
    <Conan-boost_system-Root>C:/.conan/qdrztniy/1</Conan-boost_system-Root>
....
<ClCompile>
      <AdditionalIncludeDirectories>...C:/.conan/qdrztniy/1/system/include;
      C:/.conan/shtadvqh/1/rational/include;
      C:/.conan/16iteq_w/1/winapi/include;
....
    <Link>
      <AdditionalLibraryDirectories>...C:/.conan/qdrztniy/1/system/lib;
      C:/.conan/shtadvqh/1/rational/lib;
      C:/.conan/16iteq_w/1/winapi/lib;
....  <AdditionalDependencies>
     ....  boost_atomic.lib;
      boost_filesystem.lib;
      boost_system.lib;
      boost_type_erasure.lib;
      boost_log_setup.lib;
      boost_math_c99.lib;
...  libboost_exception.lib;
      lzma.lib;
      libboost_system.lib;
      libboost_math_c99.lib;
      libboost_math_c99f.lib;
...
<PreprocessorDefinitions>LZMA_API_STATIC;BOOST_ALL_NO_LIB=1;BOOST_USE_STATIC_LIBS;_NO_ASYNCRTIMP;%(PreprocessorDefinitions)</PreprocessorDefinitions>

**Comment by WolfgangVogl** [comment]
Seems that setting skip_lib_rename to true solves the problem...

**Comment by lasote** [comment]
Yes, other approach is remove the `set(Boost_USE_STATIC_LIBS ON)`

**Comment by WolfgangVogl** [comment]
But removing the set(Boost_USE_STATIC_LIBS ON) part prevents using the static libs?!

**Comment by lasote** [comment]
No, Conan will manage to link with the correct package, because the package used only contains the static libs ( => with option `-o shared=False` (default)). That variable and much other stuff are consequences of not having a proper package manager.

**Comment by WolfgangVogl** [comment]
I've tried without the BOOST_USE_STATIC_LIBS directive but i seems that this doesn't help at all:
      <PreprocessorDefinitions>LZMA_API_STATIC;BOOST_AUTO_LINK_NOMANGLE;BOOST_ALL_NO_LIB;_NO_ASYNCRTIMP;%(PreprocessorDefinitions)</PreprocessorDefinitions> but at the very end the linker tells me 
LINK : fatal error LNK1104: cannot open file 'libboost_system-vc141-mt-sgd-x32-1_67.lib'

It seems that this problem isn't releated to conan - seems like a boost problem? somethere the boost_all_no_lib is ignored?

**Comment by lasote** [comment]
I don't think there is an issue with Boost but with the evil combination of CMake and the find package functionality. I don't know if `BOOST_AUTO_LINK_NOMANGLE` could be affecting too.

**Comment by WolfgangVogl** [comment]
Sounds really bad. At the moment i try to deal without the boost magic link options (setting BOOST_ALL_NO_LIB=1) and skipping the renaming in the boost recipe.
(If renaming the boost packages to the "no mangle" version I'm getting the cannot open file 'libboost_system-vc....' message).
At the moment it seems to work! Thanks for your help!
