### ISSUE TITLE
cross-compile for QNX: gen "cmake_find_package" can't find libs

### ISSUE THREAD

**Issue by Johnnyxy** [conan-community/conan-boost#148]
Hi there,
I am using Conan 1.6.1 on Windows (7; x64) with Boost 1.67.0 with the fancy pretty good "cmake_find_package"-generator. The best thing to seperate Conan and CMake and is much more traceable if something odd happens. The generator generates the Find-Module for Boost. It places the lib names provided by the recipe into the boost_LIBRARY_LIST variable.

`SET(boost_LIBRARY_LIST boost_wave boost_container boost_contract ...`

Now after that the libraries are searched by the CMake `find_library` command with the given library name from the list above.

Windows
---------
On Windows the files it has to find are named like this: boost_wave.lib boost_container.lib ...
`find_library` finds them and everything is good to go.

QNX
-----
On QNX the files it has to find are named like this: boost_wave.a boost_container.a ...
`find_library` cannot find them.

reason
-------
The reason behind this is propably that CMake's find_library does not search for `<name>.{a;so}` for the [QNX system](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html).
In the end find_library says that it cannot find e.g. _"boost_wave"_ because it did not search for _"boost_wave.a"_ just for _"libboost_wave.a"_ and maybe (I am unsure) just the plain name _"boost_wave"_.

see the find_library search modifying variables:
[CMAKE_FIND_LIBRARY_PREFIXES](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_LIBRARY_PREFIXES.html): lib
[CMAKE_FIND_LIBRARY_SUFFIXES](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_LIBRARY_SUFFIXES.html): .so;.a

workaround
------------
I added the following line directly in front of the _find_library_ command in the generated Findboost.cmake
`list (APPEND CMAKE_FIND_LIBRARY_PREFIXES "")`
so that the content of CMAKE_FIND_LIBRARY_PREFIXES is "lib;" (prefix "lib" and "") and find_library found everything.
But as the Find-file is generated this is no persistent solution.

So I added the same line to my CMakeLists.txt directly in front of
`find_package (boost 1.67.0 REQUIRED ...)`
and it worked.

aftermath
----------
As I am unsure who is _"responsible"_ for a clean solution. I opened a issue on gitlab at CMake. One CMake official replied that he never saw a system that does not use `lib<name>.{a;so}`. As I concur that this is odd for *nix systems but still a scenario.

One can find the CMake issue [here](https://gitlab.kitware.com/cmake/cmake/issues/18285#note_448792).

From my point of view I see nothing that stays against "no-prefix" as additional default entry in CMAKE_FIND_LIBRARY_PREFIXES.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#78
