### ISSUE TITLE
Invalid c++ standard used when building

### ISSUE THREAD

**Issue by krojew** [conan-community/conan-boost#149]
Due to https://github.com/boostorg/system/issues/26 c++14 flag needs to be explicitly passed when building boost with clang.

**Comment by lasote** [comment]
Which operating system? Android?

**Comment by krojew** [comment]
All systems - it's a compiler issue, not a system one.

**Comment by krojew** [comment]
In such cases you need to pass `cxxstd=14` to b2.

**Comment by lasote** [comment]
But what are the consequences of not passing the flag? Because it builds correctly with clang: https://travis-ci.org/conan-community/conan-boost

**Comment by krojew** [comment]
Without this change it's not possible to link against boost when using clang with c++ >= 14. If you take a look at the issue from upstream, there's a big discussion about it and breaking binary compatibility.

**Comment by krojew** [comment]
Here the relevant discussion: http://boost.2283326.n4.nabble.com/ABI-issues-with-std-td4704156.html

**Comment by Quincunx271** [comment]
I'm pretty sure this just bit me hard. The prebuilt package that was selected doesn't seem to be ABI compatible with the compilation flags I was using (`-std=c++17`). Rather than being a link-time failure, this was a runtime error

**Comment by krojew** [comment]
Any update?

**Comment by theirix** [comment]
Confirmed it too, this fails with apple-clang 10 and clang 10.
Minimal example: https://github.com/theirix/boost-system-cxxstd-test

**Comment by lasote** [comment]
I've merged #152, the new packages will be available in some hours when the CI ends. Please report if any issue.

https://ci.appveyor.com/project/lasote/conan-boost-su63s
https://travis-ci.org/conan-community/conan-boost

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#77
