### ISSUE TITLE
Travis cannot find boost_system

### ISSUE THREAD

**Issue by rllola** [conan-community/conan-boost#150]
I am trying to build libtorrent on travis iwth the new boost version (1.68).

I can build locally but on travis it fails to find the boost_system lib. Could someone tell me what I am doing wrong ?

https://travis-ci.org/rllola/zeronet-torrent-plugin/jobs/421452715

**Comment by lasote** [comment]
> CMake Warning at /usr/local/cmake-3.9.2/share/cmake-3.9/Modules/FindBoost.cmake:767 (message):
  Imported targets not available for Boost version 106800
Call Stack (most recent call first):
  /usr/local/cmake-3.9.2/share/cmake-3.9/Modules/FindBoost.cmake:871 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/cmake-3.9.2/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:269 (find_package)

I think probably you need a newer CMake installed on travis.

**Comment by rllola** [comment]
My problem is with the linux build. I have another problem for Mac but it is not link to this one.

**Comment by rllola** [comment]
It does build now. Unfortunately I don't know why... I am closing this.
