### ISSUE TITLE
Boost fails to build for iOS with wrong archiver

### ISSUE THREAD

**Issue by zhuhaow** [conan-community/conan-boost#156]
Related issue: https://github.com/conan-io/conan/issues/3514

boost expect libtool as the archiver instead of ar when building for iOS.

In cross compiling profile, such as https://github.com/theodelrieu/conan-darwin-toolchain/blob/release/1.0/conanfile.py, the env variable AR is set to ar and later the boost package will pick that up https://github.com/conan-community/conan-boost/blob/6b6a3c9bc8f07824ec3932422c9ba14311707c48/conanfile.py#L252 which will set the archiver to ar where the build will fail as the building script expect libtool.

A reasonable workaround is simply do not use AR/RANLIB env if we are building boost for iOS, which is odd but should always work. Other way is to use some env variable defining the libtool to use, this requires conan defines a new env variable for libtool at least in conan community I think.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#76
