### ISSUE TITLE
Undefined Reference using Boost.Serialization

### ISSUE THREAD

**Issue by Romain-P** [conan-community/conan-boost#159]
You can test it yourself, I'm on a simple os (Debian Linux)

- conanfile.txt

```
[generators]
cmake

[requires]
boost/1.68.0@conan/stable

[options]
boost:shared=True

[imports]
```

- CMakeList.txt

```
cmake_minimum_required(VERSION 3.10)
project(server CXX)

include(conanbuildinfo.cmake)
conan_basic_setup()

add_executable(babel_server src/main.cpp)
target_link_libraries(babel_server ${CONAN_LIBS})
```

- main.cpp

```cpp
#include <boost/archive/text_oarchive.hpp>
#include <fstream>

int main(int ac, char *args[]) {
    std::ofstream ofs("test");
    boost::archive::text_oarchive writer(ofs);
}
```

This commands line successed: `./conan install . --build missing && cmake . `  All dependencies are installed.  
But when I'm trying to compile using `make`, Im getting a linker error (undefined ref) :

```
CMakeFiles/babel_server.dir/src/main.cpp.o : in function « void boost::archive::save_access::save_primitive<boost::archive::text_oarchive, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::archive::text_oarchive&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) » :
main.cpp:(.text._ZN5boost7archive11save_access14save_primitiveINS0_13text_oarchiveENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRT_RKT0_[_ZN5boost7archive11save_access14save_primitiveINS0_13text_oarchiveENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRT_RKT0_]+0x2b) : undefined reference to « boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) »
collect2: error: ld returned 1 exit status
```

Im getting this error only with boost.serialization library, the rest is working well.

**Comment by lasote** [comment]
Hi! The issue is the mismatch of the used C++ library. In the `.conan/profiles/default` you have `compiler.libcxx=libstdc++` but the default of your compiler (gcc > 5, right?) is `compiler.libcxx=libstdc++11`. So when you install the dependencies with `conan install` you are getting the binaries for `libstdc++` and trying to link against `libstdc++11`.

You can read here the warning: https://docs.conan.io/en/latest/getting_started.html?highlight=libstdc#installing-dependencies
