### ISSUE TITLE
Other possible dependencies

### ISSUE THREAD

**Issue by memsharded** [conan-community/conan-boost#3]
From @Klaim feedback: http://boost.2283326.n4.nabble.com/Feedback-boost-conan-binary-packages-td4682377.html

"I believe libraries like boost.locale and boost,propertytree have other dependencies, 
like icu and tinyxml, but I'm not sure how they are currently managed."

Sure that ICU is a dependency, it can be seen in homebrew. Not high priority, but possibly you want to check them at some time.

**Comment by mcraveiro** [comment]
Hi @memsharded ICU is a dependency if you are building Boost.Locale on UNIX IIRC. But the same case applies to a lot of libraries such as Boost Iostreams (bzip, etc).

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#92
