### ISSUE TITLE
Adding a python version option

### ISSUE THREAD

**Issue by wpalfi** [conan-community/conan-boost#57]
When building with option "python", the default local python installation is used. The created boost python binary is different for different installed python versions. Using a downloaded binary on a different system may not work. How about adding an option for the python version?

- Allows choosing between multiple local python installations
- Reflects the difference in the Package ID

Could be done with a user-config.jam file.

**Comment by lasote** [comment]
Yes, it could be a good idea, any help/PR would be appreciated. I've created the recipe for 1.66.0 with many improvements, and I will maintain the recipes from that version, hopefully, next week in conan center.

**Comment by leugenea** [comment]
I've added this option.
We need to add option `python_version': ['2','3']`, remove it if `without_python=True` and some default value (I use 2).
Also we need a method `find_python` (code to run is taken from Boost configuration itself):
```
def find_python(self):
    def get_python_info(exe_path):
        if not os.path.exists(exe_path):
            return None
        info_ = str(subprocess.check_output([exe_path, "-c",
                                             "from sys import *; from platform import architecture; print('%d.%d\\n%s\\n%s\\n%s\\n%s\\n%s' % (version_info[0],version_info[1],platform,prefix,exec_prefix,executable, architecture()[0]))"]).decode(
            "ASCII"))
        values = info_.split()
        return dict(zip(["version", "platform", "prefix", "exec_prefix", "executable", "arch"], values))

    prefixes = ['/usr/bin/', '/bin/', '/usr/local/bin/'] + ['C:/Python2/', 'C:/Python3/'] + \
               ['C:/Python2{}/'.format(v) for v in [6, 7]] + ['C:/Python3{}/'.format(v) for v in range(10)]
    names = ['python', 'python2', 'python3']
    product = itertools.product(prefixes, names)
    pythons_to_try = [p + n for (p, n) in product]

    bits = "32" if self.settings.arch == "x86" else "64"

    for python_exe in pythons_to_try:
        info = get_python_info(python_exe)
        if info is not None and \
                info['version'].startswith(str(self.options.python_version)) and \
                info['arch'].startswith(bits):
            return info

    return None
```
Maybe some any platform-specific paths are needed.

In `create_user_config_jam`, after adding flags:
```
if not self.options.without_python:
    found = self.find_python()
    if found is None:
        raise Exception(
            "Required Build with python, but no python{} found".format(str(self.options.python_version)))
    self.output.warn("Found python{} in {}".format(found['version'], found['executable']))
    contents += '\nusing python : {} : {} ;'.format(found['version'], found['executable'])
```

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#91
