### ISSUE TITLE
Should other boost defines be handled via options?

### ISSUE THREAD

**Issue by KalleDK** [conan-community/conan-boost#73]
The three I know of (and use)

I think this only is needed in cpp_info and might not change how boost itself is compiled.
BOOST_ERROR_CODE_HEADER_ONLY (Is needed if system is not available)

I think these actually changes how the build ends up, and should also be in cpp_info
BOOST_SYSTEM_NO_DEPRECATED (Error if deprecated calls are used)
BOOST_ASIO_NO_DEPRECATED (Error if deprecated calls are used)

**Comment by simon-bourne** [comment]
There's also `BOOST_USE_VALGRIND` and `BOOST_USE_ASAN` in Boost Context. I don't know of any way to get a definitive list though.

**Comment by trivigy** [comment]
Is there a work around of how to set these for now?
I need to build boost with BOOST_ASIO_NO_DEPRECATED because it actually changes how the functionality works to make boost asio rely only on new classes rather than older ones. mutable_buffer vs mutable_buffers_1

**Comment by lasote** [comment]
I think some of them if they affect how is boost built, should be modeled as options in the recipe. I think there is no possible workaround but introduce the options. I would try to do it in the following days. Please write again if no news in a couple of days. Thanks

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#90
