### ISSUE TITLE
Boost 1.66.0 link problem (Windows)

### ISSUE THREAD

**Issue by db4** [conan-community/conan-boost#80]
Unfortunately the same problem exists in your build as in the bincrafters` one. I have a link error when trying to build a trivial test consisting of only

`main.cpp`
```c++
#define BOOST_TEST_MODULE Test
#include <boost/test/unit_test.hpp>
```
If you need more detail, see https://github.com/bincrafters/community/issues/94

**Comment by lasote** [comment]
Thanks for reporting, taking a look right now.

**Comment by lasote** [comment]
Could you try now? Thanks.

**Comment by db4** [comment]
I see no problem so far; looks like it has been fixed.
