### ISSUE TITLE
CMake can't find boost after conan complains boost components are 'Missing in order'

### ISSUE THREAD

**Issue by liberforce** [conan-community/conan-boost#83]
I'm trying to package https://github.com/aldebaran/libqi

So as a first step I created a very basic `conanfile.txt` there:
```
[requires]
boost/1.66.0@conan/stable
gtest/1.8.0@bincrafters/stable

[generators]
cmake

```
`conan install` step works, but conan complains that some boost components are 'Missing in order'. After that, when calling `cmake`, it fails because it can't find boost.

Here are the logs:
[cmake-error-at-boost-detection.log](https://github.com/conan-community/conan-boost/files/1728705/cmake-error-at-boost-detection.log)

I'm running conan 1.0.4, gcc-4.8, cmake 3.5.1 on Ubuntu 14.04 (yeah, don't laugh :) )

NOTE: you may need to `pip install qibuild`, the meta-build system used by libqi, which is a layer above CMake.

**Comment by lasote** [comment]
Forget the missing in order, it is a trace always shown. It means nothing. 
Could I see the CMakelist.txt? Looks like you are not including the conanbuildinfo.cmake nor calling basic setup.

**Comment by lasote** [comment]
http://docs.conan.io/en/latest/getting_started.html#id4

**Comment by liberforce** [comment]
Ok, I've been confused between `conanfile.txt` and `conanfile.py`, I opened a documentation bug about that. I indeed forgot to include the  `conanbuildinfo.cmake` and call basic setup. Sorry for the noise.
