### ISSUE TITLE
Test Fail  boost-1.66.0

### ISSUE THREAD

**Issue by KunWangV** [conan-community/conan-boost#84]
Ubuntu 16.04 , cmake 3.6.0, ref http://blog.conan.io/2018/01/30/Cross-building-Boost-Android.html
```

0% tests passed, 3 tests failed out of 3

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - TestRegex (Failed)
          2 - TestLambda (Failed)
          3 - TestRegexNew (Failed)
Errors while running CTest
ERROR: DefaultName/0.1@PROJECT: Error in test() method, line 38
        self.run('ctest --output-on-error -C %s' % bt)
        ConanException: Error 2048 while executing ctest --output-on-error -C Release

```

**Comment by lasote** [comment]
If you are cross-building to Android it is ok that the tests fail, because you cannot run Android libraries in your Ubuntu. So, the libraries are built OK, go ahead with the rest of the blog post, and any other problem just write.
