### ISSUE TITLE
Split package into Boost subcomponents?

### ISSUE THREAD

**Issue by Quincunx271** [conan-community/conan-boost#86]
Boost is rather large. Just downloading it can take some time. Furthermore, not all Boost libraries depend on all others. For example, Boost Preprocessor doesn't have any dependencies. Should this single Boost package be split into all the different Boost components? This would allow users to specify that they only want to use part of Boost, and they wouldn't have to wait for all the rest of Boost to download.

[Vcpkg](https://github.com/Microsoft/vcpkg/) has done this. IIUC, their system works by having all the different _boost-foo_ libraries depend on the correct other _boost-bar_ libraries, with the main _boost_ library depending on all of the Boost components.

**Comment by lasote** [comment]
You are looking for modular boost from bincrafters, read here: https://bincrafters.github.io/
**vcpkg** just copied from them.

**Comment by Quincunx271** [comment]
I did not know about this. I only found [conan/conan-center](https://bintray.com/conan/conan-center) and [conan/conan-transit](https://bintray.com/conan/conan-transit). Now I know there's a [bincrafters/public-conan]( ttps://bintray.com/bincrafters/public-conan). Yes, that is exactly what I was looking for.

Are there any other conan repositories that I should know about when I want to look for libraries? I was unable to find the bincrafters/public-conan when looking for them; maybe there are some others I should be aware of.

**Comment by lasote** [comment]
You are right:
http://docs.conan.io/en/latest/uploading_packages/remotes.html#official-repositories
