### ISSUE TITLE
conan package info lists either serialization or wserialization but not both

### ISSUE THREAD

**Issue by ebclark2** [conan-community/conan-boost#88]
The conan package will sometimes use boost_serialization and other times use boost_wserialization.  This seems to be caused by the ordering logic in package_info and the endswith() call from the contents of list_list.  Since there are two libraries ending in serialization whichever is listed last by tools.collect_libs() is the one that ends up in the package info.  

One possible fix is to replace serialization in lib_list with " '_serialization', '_wserialization'".

**Comment by lasote** [comment]
It should be fixed, it will take some hours to upload all the packages.
Thanks for reporting.

**Comment by ebclark2** [comment]
Thank you!
