### ISSUE TITLE
CMake 3.11 cannot find the boost 1.66.0 static libraries on Windows, naming convention issue

### ISSUE THREAD

**Issue by aallrd** [conan-community/conan-boost#89]
Hello,
I found an issue while trying to use CMake 3.11 to find the boost 1.66.0 static libraries generated by the `release/1.66.0` recipe on Windows.
CMake 3.11 seems to be required to use boost 1.66.0.
I am using Visual Studio 2017 to generate the boost 1.66.0 static libraries.

```
Existing packages for recipe boost/1.66.0@aallard/testing:

    Package_ID: 267704336ef55cc31615a75f0c9b0650a9afb8a9
        [options]
            header_only: False
            shared: False
            without_atomic: False
            without_chrono: False
            without_container: False
            without_context: False
            without_coroutine: False
            without_date_time: False
            without_exception: False
            without_fiber: False
            without_filesystem: False
            without_graph: False
            without_graph_parallel: False
            without_iostreams: False
            without_locale: False
            without_log: False
            without_math: False
            without_mpi: False
            without_program_options: False
            without_python: True
            without_random: False
            without_regex: False
            without_serialization: False
            without_signals: False
            without_stacktrace: False
            without_system: False
            without_test: False
            without_thread: False
            without_timer: False
            without_type_erasure: False
            without_wave: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 15
            os: Windows
        [requires]
            bzip2/1.0.6@conan/stable:ce1f8ff23addde793223a2a82ed7fe355c57a589
            zlib/1.2.11@conan/stable:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
        Outdated from recipe: False
```

Here is the CMakeLists.txt to reproduce the issue:
```
project(test)
cmake_minimum_required(VERSION 3.11)
set(Boost_DEBUG 1)
find_package(Boost COMPONENTS regex REQUIRED)
add_executable(regex_exe regex.cpp)
target_link_libraries(regex_exe ${Boost_LIBRARIES})
```

When running the below CMake command, I get an error:
```
> cmake -G "Visual Studio 15 2017 Win64" -DBOOST_ROOT="D:\.conan\ohsje4\1"
-- [ C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1670 ] Searching for REGEX_LIBRARY_RELEASE: boost_regex-vc141-mt-x64-1_66;boost_regex-vc141-mt;boost_regex-vc140-mt-x64-1_66;boost_regex-vc140-mt;boost_regex-mt-x64-1_66;boost_regex-mt;boost_regex
-- [ C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1721 ] Searching for REGEX_LIBRARY_DEBUG: boost_regex-vc141-mt-gd-x64-1_66;boost_regex-vc141-mt-gd;boost_regex-vc140-mt-gd-x64-1_66;boost_regex-vc140-mt-gd;boost_regex-mt-gd-x64-1_66;boost_regex-mt-gd;boost_regex-mt;boost_regex
-- [ C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1795 ] Boost_FOUND = 1
CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1956 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.66.0

  Boost include path: D:/.conan/ohsje4/1/include

  Could not find the following Boost libraries:

          boost_regex

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)
```

The `regex` library (and all the other libraries) is renamed from `libboost_regex-vc141-mt-x64-1_66.lib` to `boost_regex-vc141-mt-1_66.lib` by the `renames_to_make_cmake_find_package_happy()` function.

It seems that CMake requires the `-x64-` particule in the name of the library, but not the `lib` prefix indeed.

- libboost_regex-vc141-mt-x64-1_66.lib -> not found
- libboost_regex-vc141-mt-1_66.lib -> not found
- boost_regex-vc141-mt-x64-1_66.lib -> found

I guess the fix would be to tweak the `renames_to_make_cmake_find_package_happy()`.
I can work on a pull request starting next week.

**Comment by lasote** [comment]
Thanks, I will take a look. It is **very** hard to keep all the CMake versions happy...

**Comment by aallrd** [comment]
I understand your pain... :)
I'll work on a PR this morning to fix the current behavior in the meantime since CMake 3.11 is indeed required to work with boost 1.66.0:
- [FindBoost: Add 1.66.0 support](https://gitlab.kitware.com/cmake/cmake/merge_requests/1625)
- [FindBoost: Upgrade to Boost 1.66.0 and allow new library files names layout.](https://gitlab.kitware.com/cmake/cmake/merge_requests/1621)

I see that you have referenced this issue as **reintroduce FindBoost.cmake**, does that mean that you are planning on embedding the latest BoostFinder.cmake directly in the recipe?

Maybe it would be interesting to add some kind of requirement mechanism for build tools like the one for the packages, in order to make sure a minimum version is installed:
```
    def build_requirements(self):
            self.build_requires(["cmake": ">=3.11.0"])
```

**Comment by lasote** [comment]
> I see that you have referenced this issue as reintroduce FindBoost.cmake, does that mean that you are planning on embedding the latest BoostFinder.cmake directly in the recipe?

No, It is a nightmare, because once you enter in the custom FindBoost.cmake you cannot fall back to the CMake original one, so you become maintaining both Boost and CMake for all the versions combinations.

About the CMake build require. It could be recommended in the README or with some warning in the recipe, for sure, but forcing to use a build system version is not something that users want.

**Comment by mgalimullin** [comment]
Hello! I have same problem with renaming .lib files. Could you do renaming like option?
https://ci.appveyor.com/project/mgalimullin/libcds/build/1.0.225/job/en80giwen89ba53n

**Comment by lasote** [comment]
Hello, I updated some days ago the recipe to generate simple names that any CMake is able to find with the findBoost module.
@aallrd did you manage to try it again? 
@mgalimullin I'm not sure if the problem is the same, I looked at your project and I'm not sure who is setting the boost library name to that name. Are you using CMake find package? I can't see the inclusion of `conanbuildinfo` in your CMakelists.txt.

**Comment by mgalimullin** [comment]
Sorry. Yes, it is other problem, but it is problem with renaming.
No, there don't use cmake, we use msvc-solution.
I would like to use conan to the way of getting boost and I would not like to do changes in the solution.
A target of solution expects standard name of boost lib but unfortunately the name changes after build

**Comment by aallrd** [comment]
@lasote I confirm that both the master conan recipe and my small test project consuming it are now working successfully with CMake 3.10.2 and 3.11.0-rc3.
I'll mark this issue closed, thank you :+1: .

**Comment by lasote** [comment]
@mgalimullin Then you should use the `visual_studio` generator and import the property files. In that file will be the real name of every dependency.

**Comment by mgalimullin** [comment]
@lasote  Ok. Thank you! I'll try it.

**Comment by gagelarsen** [comment]
We are having a similar issue. Here is a link to our appveyor:
https://ci.appveyor.com/project/Aquaveo/xmscore/build/1.0.0-64

and a link to our repo:
https://github.com/Aquaveo/xmscore

We used cmake 3.11.0 r4 and then we tried 3.10.3 as well with the same problem.

After conan installing boost we have ./lib/boost_<name>.lib
when we try to compile it errors out looking for 'libboost_<name>-vc120-mt-gd-x32-1_66.lib'
If we rename the libraries it errors out looking for boost_<name>.lib
If we have both the original and the renamed it works.

Any ideas?

**Comment by lasote** [comment]
I think the issue is using the Boost auto-linking. Probably in both cases.

**Comment by helmesjo** [comment]
@lasote What do you mean? What is the solution?
