### ISSUE TITLE
reintroduce FindBoost.cmake

### ISSUE THREAD

**Issue by a-teammate** [conan-community/conan-boost#91]
Hey there,

in previous versions two findboost.cmake were shipped along with the Conan package.
I guess it had been removed for the reason that findboost should be CMake territory and it would be easier not to override these files and being in need of updating them, is that correct?

Currently, this package only works flawlessly with CMake 3.9 and CMake 3.10 (3.8 warns, 3.11 fails).
Not really much less of a burden to maintain it seems.

Would a PR replacing the `renames_to_make_cmake_find_package_happy`-function with one shipped findboost.cmake (for cmake > 3.4 only probably) find recognition?

This file only needs to be updated with new boost versions, not with new cmake versions, which could make it easier to maintain them.
Two findBoost-files to support even cmake <3.4 is probably a bit overkill.

**Comment by lasote** [comment]
I removed it because maintaining a `findboost.cmake` to cover the CMake lacks is a nightmare, if you override it you can't reach the original provided by CMake and you are always out to date for newer versions.
Which are the errors with 3.11?

**Comment by a-teammate** [comment]
Okay, I can imagine that these files were always making trouble.

The reason I was looking for a findBoost.cmake is because it is a quick way to acquire only a subset of Boost in different modules (`Boost::filesystem` instead of `Conan::Boost`). Maybe a modular boost https://github.com/conan-community/conan-boost/issues/86 will help then (as soon as that one is ready).

I'll close this issue then and will simply stay away from findBoost. Thank you for your support

**Comment by lasote** [comment]
I'm working in a library rename even more compatible with CMake, just names following the "boost_xxx" pattern: e.k "boost_regex.lib". I don't know if it is going to work with any CMake version but it should, because it looks like CMake is, after trying other combinations, trying the very basic name. I'm merging the #94, so in some hours you could try it.
