### ISSUE TITLE
Sourceforge link is broken

### ISSUE THREAD

**Issue by JakubSzczerbinski** [conan-community/conan-boost#92]
I couldn't download from sourceforge from browser too, it would be super nice if there was a fallback download link.

~~~
ERROR: boost/1.66.0@conan/stable: Error in source() method, line 65
	tools.download(url, zip_name)
	ConanException: Error 404 downloading file http://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
~~~

**Comment by db4** [comment]
Same problem for me; [boost.org Downloads](http://www.boost.org/users/download) now suggests bintray.com as a download site.

**Comment by lasote** [comment]
I will fix it asap, thanks
