### ISSUE TITLE
Error when building Android x86_64

### ISSUE THREAD

**Issue by leugenea** [conan-community/conan-boost#95]
When building for x86_64 Android version, in `get_build_cross_flags`:
`flags.append('architecture=%s' % ('arm' if arch.startswith('arm') else arch))` .
The problem is that Boost doesn't have 'x86_64' architecture option, this is an error:
```
boost_1_65_1/tools/build/src/build/feature.jam:494: in feature.validate-value-string from module feature
error: "x86_64" is not a known value of feature <architecture>
error: legal values: "x86" "ia64" "sparc" "power" "mips1" "mips2" "mips3" "mips4" "mips32" "mips32r2" "mips64" "parisc" "arm" "combined" "combined-x86-power"
```
So, looks like we should write something like:
```
architecrure_flag = arch
if arch.startswith('arm'):
    architecrure_flag = 'arm'
elif arch.startswith('x86'):
    architecrure_flag = 'x86'
flags.append('architecture=%s' % architecrure_flag)
```

**Comment by lasote** [comment]
I pushed to the `testing/1.66.0` branch. Could you try it? You can clone this, repo, checkout the  branch and export the modified recipe with: `conan export . conan/stable`. It will override the recipe in your local cache.

**Comment by leugenea** [comment]
I’ll check this tomorrow.

**Comment by leugenea** [comment]
Looks OK.

**Comment by lasote** [comment]
Sorry I forgot about this. I've pushed to the release branch and the packages should be available during the day (the time it takes the CI). Thanks! :)
